name = "Prakriti's personal website"
description = "I'm a sophomore double majoring in CS and Mathematics"
license = "MIT"
homepage = "https://github.com/prakriti0007/prakritinepal.me"
min_version = "0.17.0"
demo = "https:/prakritinepal.me/"

[author]
name = "prakriti"
homepage = "https://prakritinepal.me"

[original]
author = "nanxiaobei"
homepage = "https://lee.so/"
repo = "https://github.com/nanxiaobei/hugo-paper"
